# Generated by Django 4.2.10 on 2026-06-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='居住地址')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('active', '在矫中'), ('completed', '已解矫'), ('suspended', '暂停')], default='active', max_length=20, verbose_name='状态')),
                ('correction_type', models.CharField(max_length=50, verbose_name='矫正类型')),
                ('correction_start', models.DateField(verbose_name='矫正开始日期')),
                ('correction_end', models.DateField(verbose_name='矫正结束日期')),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='家经度')),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='家纬度')),
                ('allowed_deviation', models.FloatField(default=500.0, verbose_name='允许偏离距离(米)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='correction_objects/', verbose_name='照片')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_judicial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_judicial', to=settings.AUTH_USER_MODEL, verbose_name='负责司法所')),
                ('assigned_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_worker', to=settings.AUTH_USER_MODEL, verbose_name='负责社工')),
            ],
            options={
                'verbose_name': '矫正对象',
                'verbose_name_plural': '矫正对象',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='计划走访日期')),
                ('plan_type', models.CharField(max_length=50, verbose_name='走访类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='是否自动生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visit_plans', to=settings.AUTH_USER_MODEL, verbose_name='负责社工')),
                ('correction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to='correction.correctionobject', verbose_name='矫正对象')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visit_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '走访计划',
                'verbose_name_plural': '走访计划',
                'ordering': ['-plan_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='走访时间')),
                ('visit_way', models.CharField(choices=[('home', '入户走访'), ('telephone', '电话走访'), ('video', '视频走访'), ('office', '司法所报到'), ('other', '其他')], max_length=20, verbose_name='走访方式')),
                ('talk_summary', models.TextField(verbose_name='谈话摘要')),
                ('risk_change', models.CharField(blank=True, choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], max_length=20, null=True, verbose_name='风险变化')),
                ('location_valid', models.BooleanField(default=True, verbose_name='定位是否有效')),
                ('location_deviation', models.FloatField(blank=True, null=True, verbose_name='定位偏离距离(米)')),
                ('photos', models.JSONField(default=list, verbose_name='走访照片')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('correction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='correction.correctionobject', verbose_name='矫正对象')),
                ('visit_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_record', to='correction.visitplan', verbose_name='关联走访计划')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to=settings.AUTH_USER_MODEL, verbose_name='走访人')),
            ],
            options={
                'verbose_name': '走访记录',
                'verbose_name_plural': '走访记录',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskLevelChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], max_length=20, verbose_name='原风险等级')),
                ('to_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], max_length=20, verbose_name='新风险等级')),
                ('reason', models.TextField(verbose_name='调整原因')),
                ('regenerated_plan', models.BooleanField(default=False, verbose_name='是否已重生成计划')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调整时间')),
                ('correction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_changes', to='correction.correctionobject', verbose_name='矫正对象')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '风险等级变更',
                'verbose_name_plural': '风险等级变更',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missed_visit', '漏访提醒'), ('location_deviation', '定位偏离'), ('risk_change', '风险变更'), ('system', '系统通知')], max_length=30, verbose_name='通知类型')),
                ('level', models.CharField(choices=[('normal', '普通'), ('warning', '警告'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='通知级别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联记录ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('correction_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='correction.correctionobject', verbose_name='关联矫正对象')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='纬度')),
                ('is_deviated', models.BooleanField(default=False, verbose_name='是否偏离')),
                ('deviation_distance', models.FloatField(blank=True, null=True, verbose_name='偏离距离(米)')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址描述')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('correction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_records', to='correction.correctionobject', verbose_name='矫正对象')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '定位记录',
                'verbose_name_plural': '定位记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(verbose_name='反馈日期')),
                ('behavior_situation', models.TextField(verbose_name='帮教情况')),
                ('mental_state', models.TextField(blank=True, verbose_name='思想动态')),
                ('life_condition', models.TextField(blank=True, verbose_name='生活状况')),
                ('work_study', models.TextField(blank=True, verbose_name='工作学习情况')),
                ('problems', models.TextField(blank=True, verbose_name='存在问题')),
                ('suggestions', models.TextField(blank=True, verbose_name='意见建议')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('reviewed', '已审核')], default='submitted', max_length=20, verbose_name='状态')),
                ('review_remark', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('correction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_feedbacks', to='correction.correctionobject', verbose_name='矫正对象')),
                ('family_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='家属')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '家属帮教反馈',
                'verbose_name_plural': '家属帮教反馈',
                'ordering': ['-feedback_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('spouse', '配偶'), ('parent', '父母'), ('child', '子女'), ('sibling', '兄弟姐妹'), ('other', '其他')], max_length=20, verbose_name='与矫正对象关系')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('correction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='correction.correctionobject', verbose_name='矫正对象')),
                ('family_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_relations', to=settings.AUTH_USER_MODEL, verbose_name='家属用户')),
            ],
            options={
                'verbose_name': '家属关系',
                'verbose_name_plural': '家属关系',
                'unique_together': {('correction_object', 'family_user')},
            },
        ),
    ]
